import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'ar', 'zh_Hans', 'fr', 'de', 'pt', 'ru', 'es', 'tr'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? arText = '',
    String? zh_HansText = '',
    String? frText = '',
    String? deText = '',
    String? ptText = '',
    String? ruText = '',
    String? esText = '',
    String? trText = '',
  }) =>
      [
        enText,
        arText,
        zh_HansText,
        frText,
        deText,
        ptText,
        ruText,
        esText,
        trText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // language_screen
  {
    'k7b696sj': {
      'en': 'Change Language',
      'ar': 'تغيير اللغة',
      'de': 'Sprache ändern',
      'es': 'Cambiar idioma',
      'fr': 'Changer de langue',
      'pt': 'Mudar idioma',
      'ru': 'Изменение языка',
      'tr': 'Dili değiştir',
      'zh_Hans': '改变语言',
    },
    'a0fyjqsm': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'tr': 'Kaydetmek',
      'zh_Hans': '节省',
    },
    'i9m3bsou': {
      'en': 'Change Language',
      'ar': 'تغيير اللغة',
      'de': 'Sprache ändern',
      'es': 'Cambiar idioma',
      'fr': 'Changer de langue',
      'pt': 'Mudar idioma',
      'ru': 'Изменение языка',
      'tr': 'Dili değiştir',
      'zh_Hans': '改变语言',
    },
  },
  // login_screen
  {
    'th4sex5e': {
      'en': 'Welcome,',
      'ar': 'مرحباً،',
      'de': 'Willkommen,',
      'es': 'Bienvenido,',
      'fr': 'Accueillir,',
      'pt': 'Bem-vindo,',
      'ru': 'Добро пожаловать,',
      'tr': 'Hoş geldin,',
      'zh_Hans': '欢迎，',
    },
    'l0fds6fb': {
      'en': 'Sign In to continue',
      'ar': 'قم بتسجيل الدخول للمتابعة',
      'de': 'Melden Sie sich an, um fortzufahren',
      'es': 'Inicia sesión para continuar',
      'fr': 'Connectez-vous pour continuer',
      'pt': 'Faça login para continuar',
      'ru': 'Войдите, чтобы продолжить',
      'tr': 'Devam etmek için oturum açın',
      'zh_Hans': '登录以继续',
    },
    '6aojv8sy': {
      'en': '',
      'ar': 'بريد إلكتروني',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'pt': 'E-mail',
      'ru': 'Электронная почта',
      'tr': 'E-posta',
      'zh_Hans': '电子邮件',
    },
    'imh1zi9g': {
      'en': 'Email Address',
      'ar': 'عنوان البريد الإلكتروني',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'tr': 'E-posta Adresi',
      'zh_Hans': '电子邮件地址',
    },
    'jzokmre4': {
      'en': '',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'pt': 'Senha',
      'ru': 'Пароль',
      'tr': 'Şifre',
      'zh_Hans': '密码',
    },
    '497bukjd': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'pt': 'Senha',
      'ru': 'Пароль',
      'tr': 'Şifre',
      'zh_Hans': '密码',
    },
    'ycnv65i3': {
      'en': 'Forgot Password?',
      'ar': 'هل نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'pt': 'Esqueceu sua senha?',
      'ru': 'Забыли пароль?',
      'tr': 'Parolanızı mı unuttunuz?',
      'zh_Hans': '忘记密码？',
    },
    'bltmxua3': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'pt': 'Conecte-se',
      'ru': 'Авторизоваться',
      'tr': 'Giriş yapmak',
      'zh_Hans': '登录',
    },
    'anao6v0h': {
      'en': 'Don\'t have an Account?',
      'ar': 'ليس لديك حساب؟',
      'de': 'Sie haben kein Konto?',
      'es': '¿No tienes una cuenta?',
      'fr': 'Vous n\'avez pas de compte ?',
      'pt': 'Não tem uma conta?',
      'ru': 'У вас нет учетной записи?',
      'tr': 'Hesabınız yok mu?',
      'zh_Hans': '没有帐户？',
    },
    'nnbrrxo7': {
      'en': 'Register',
      'ar': 'تسجيل الدخول',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'pt': 'Conecte-se',
      'ru': 'Авторизоваться',
      'tr': 'Giriş yapmak',
      'zh_Hans': '登录',
    },
    'bqwu8rgt': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // forgot_password_screen
  {
    'rj63thse': {
      'en': 'Forgot Password?',
      'ar': 'هل نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'pt': 'Esqueceu sua senha?',
      'ru': 'Забыли пароль?',
      'tr': 'Parolanızı mı unuttunuz?',
      'zh_Hans': '忘记密码？',
    },
    '1n44dlwi': {
      'en': 'Enter email to reset your password',
      'ar': 'أدخل البريد الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك',
      'de': 'Geben Sie Ihre E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen',
      'es': 'Ingrese su correo electrónico para restablecer su contraseña',
      'fr': 'Entrez votre email pour réinitialiser votre mot de passe',
      'pt': 'Digite o e-mail para redefinir sua senha',
      'ru': 'Введите адрес электронной почты, чтобы сбросить пароль',
      'tr': 'Şifrenizi sıfırlamak için e-posta girin',
      'zh_Hans': '输入电子邮件以重置您的密码',
    },
    'l4ruwklp': {
      'en': '',
      'ar': 'بريد إلكتروني',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'pt': 'E-mail',
      'ru': 'Электронная почта',
      'tr': 'E-posta',
      'zh_Hans': '电子邮件',
    },
    '6hhx5jq0': {
      'en': 'Email Address',
      'ar': 'عنوان البريد الإلكتروني',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'tr': 'E-posta Adresi',
      'zh_Hans': '电子邮件地址',
    },
    'v0tt8jx2': {
      'en': 'Send Link',
      'ar': 'أرسل الرابط',
      'de': 'Link senden',
      'es': 'Enviar enlace',
      'fr': 'Envoyer un lien',
      'pt': 'Enviar Link',
      'ru': 'Отправить ссылку',
      'tr': 'Link gönder',
      'zh_Hans': '发送链接',
    },
    '86r7yo15': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // reset_password_screen
  {
    '63rrj7rl': {
      'en': 'Reset Password',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'fr': 'réinitialiser le mot de passe',
      'pt': 'Redefinir senha',
      'ru': 'Сброс пароля',
      'tr': 'Şifreyi yenile',
      'zh_Hans': '重设密码',
    },
    'ur3ioc8e': {
      'en': 'Set a new password below',
      'ar': 'قم بتعيين كلمة مرور جديدة أدناه',
      'de': 'Legen Sie unten ein neues Passwort fest',
      'es': 'Establece una nueva contraseña a continuación',
      'fr': 'Définissez un nouveau mot de passe ci-dessous',
      'pt': 'Defina uma nova senha abaixo',
      'ru': 'Установите новый пароль ниже',
      'tr': 'Aşağıda yeni bir şifre belirleyin',
      'zh_Hans': '在下面设置新密码',
    },
    '36ya5tzs': {
      'en': '',
      'ar': 'كلمة المرور الجديدة',
      'de': 'Neues Kennwort',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'pt': 'Nova Senha',
      'ru': 'Новый пароль',
      'tr': 'Yeni Şifre',
      'zh_Hans': '新密码',
    },
    'kxoh6gx0': {
      'en': 'New Password',
      'ar': 'كلمة المرور الجديدة',
      'de': 'Neues Kennwort',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'pt': 'Nova Senha',
      'ru': 'Новый пароль',
      'tr': 'Yeni Şifre',
      'zh_Hans': '新密码',
    },
    'rxl94iq1': {
      'en': '',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'pt': 'Confirme sua senha',
      'ru': 'Подтвердите пароль',
      'tr': 'Şifreyi Onayla',
      'zh_Hans': '确认密码',
    },
    'agbevg17': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'pt': 'Confirme sua senha',
      'ru': 'Подтвердите пароль',
      'tr': 'Şifreyi Onayla',
      'zh_Hans': '确认密码',
    },
    'oe5hp570': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'tr': 'Kaydetmek',
      'zh_Hans': '节省',
    },
    '6mrsvz9d': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // dashboard
  {
    '6hsy28xo': {
      'en': 'Total Active \nUsers',
      'ar': 'إجمالي النشاط\nالمستخدمين',
      'de': 'Insgesamt aktiv\nBenutzer',
      'es': 'Total Activo\nUsuarios',
      'fr': 'Actif total\nUtilisateurs',
      'pt': 'Totalmente Ativo\nUsuários',
      'ru': 'Всего активных\nПользователи',
      'tr': 'Toplam Aktif\nKullanıcılar',
      'zh_Hans': '总活跃度\n用户',
    },
    'eck7f7xr': {
      'en': 'Total Deactivated\nUsers',
      'ar': 'إجمالي معطل\nالمستخدمين',
      'de': 'Total deaktiviert\nBenutzer',
      'es': 'Total desactivado\nUsuarios',
      'fr': 'Total désactivé\nUtilisateurs',
      'pt': 'Totalmente Desativado\nUsuários',
      'ru': 'Всего деактивировано\nПользователи',
      'tr': 'Toplam Devre Dışı Bırakıldı\nKullanıcılar',
      'zh_Hans': '全部停用\n用户',
    },
    'rxccenn6': {
      'en': 'Total Active\nVcards',
      'ar': 'إجمالي النشاط\nبطاقات V',
      'de': 'Insgesamt aktiv\nV-Karten',
      'es': 'Total Activo\ntarjetas virtuales',
      'fr': 'Actif total\nCartes virtuelles',
      'pt': 'Totalmente Ativo\nCartões virtuais',
      'ru': 'Всего активных\nВидеокарты',
      'tr': 'Toplam Aktif\nVcard\'lar',
      'zh_Hans': '总活跃度\n电子贺卡',
    },
    'u6g2qwc5': {
      'en': 'Total Deactivated\nVcards',
      'ar': 'إجمالي معطل\nبطاقات V',
      'de': 'Total deaktiviert\nV-Karten',
      'es': 'Total desactivado\ntarjetas virtuales',
      'fr': 'Total désactivé\nCartes virtuelles',
      'pt': 'Totalmente Desativado\nCartões virtuais',
      'ru': 'Всего деактивировано\nВидеокарты',
      'tr': 'Toplam Devre Dışı Bırakıldı\nVcard\'lar',
      'zh_Hans': '全部停用\n电子贺卡',
    },
    'ufd1g8fs': {
      'en': 'VCard Analytics',
      'ar': 'تحليلات VCard',
      'de': 'VCard-Analyse',
      'es': 'Análisis de tarjetas V',
      'fr': 'Analyse VCard',
      'pt': 'Análise do VCard',
      'ru': 'Видеокарта Аналитика',
      'tr': 'VCard Analizi',
      'zh_Hans': '电子名片分析',
    },
    'f1noyzo0': {
      'en': 'Month',
      'ar': 'شهر',
      'de': 'Monat',
      'es': 'Mes',
      'fr': 'Mois',
      'pt': 'Mês',
      'ru': 'Месяц',
      'tr': 'Ay',
      'zh_Hans': '月',
    },
    'lmysjehc': {
      'en': 'Income',
      'ar': 'دخل',
      'de': 'Einkommen',
      'es': 'Ingreso',
      'fr': 'Revenu',
      'pt': 'Renda',
      'ru': 'Доход',
      'tr': 'Gelir',
      'zh_Hans': '收入',
    },
    'w4yi1rza': {
      'en': 'Total Active\nVcards',
      'ar': 'إجمالي النشاط\nبطاقات V',
      'de': 'Insgesamt aktiv\nV-Karten',
      'es': 'Total Activo\ntarjetas virtuales',
      'fr': 'Actif total\nCartes virtuelles',
      'pt': 'Totalmente Ativo\nCartões virtuais',
      'ru': 'Всего активных\nВидеокарты',
      'tr': 'Toplam Aktif\nVcard\'lar',
      'zh_Hans': '总活跃度\n电子贺卡',
    },
    'dx7jboeu': {
      'en': 'Total Deactivated\nVcards',
      'ar': 'إجمالي معطل\nبطاقات V',
      'de': 'Total deaktiviert\nV-Karten',
      'es': 'Total desactivado\ntarjetas virtuales',
      'fr': 'Total désactivé\nCartes virtuelles',
      'pt': 'Totalmente Desativado\nCartões virtuais',
      'ru': 'Всего деактивировано\nВидеокарты',
      'tr': 'Toplam Devre Dışı Bırakıldı\nVcard\'lar',
      'zh_Hans': '全部停用\n电子贺卡',
    },
    '76c7kx4k': {
      'en': 'Today \nEnquiries',
      'ar': 'اليوم\nاستفسارات',
      'de': 'Heute\nAnfragen',
      'es': 'Hoy\nConsultas',
      'fr': 'Aujourd\'hui\nDemandes de renseignements',
      'pt': 'Hoje\nInquéritos',
      'ru': 'Сегодня\nЗапросы',
      'tr': 'Bugün\nAraştırma',
      'zh_Hans': '今天\n查询',
    },
    'zvfj14as': {
      'en': 'Today \nAppointments',
      'ar': 'اليوم\nتعيينات',
      'de': 'Heute\nTermine',
      'es': 'Hoy\nEquipo',
      'fr': 'Aujourd\'hui\nRendez-vous',
      'pt': 'Hoje\nCompromissos',
      'ru': 'Сегодня\nНазначения',
      'tr': 'Bugün\nRandevular',
      'zh_Hans': '今天\n预约',
    },
    'xdgkk7kf': {
      'en': 'VCard Analytics',
      'ar': 'تحليلات VCard',
      'de': 'VCard-Analyse',
      'es': 'Análisis de tarjetas V',
      'fr': 'Analyse VCard',
      'pt': 'Análise do VCard',
      'ru': 'Видеокарта Аналитика',
      'tr': 'VCard Analizi',
      'zh_Hans': '电子名片分析',
    },
    '721dm1ol': {
      'en': 'Today’s Appointments',
      'ar': 'مواعيد اليوم',
      'de': 'Die heutigen Termine',
      'es': 'Citas de hoy',
      'fr': 'Les rendez-vous d\'aujourd\'hui',
      'pt': 'Compromissos de hoje',
      'ru': 'Сегодняшние встречи',
      'tr': 'Bugünkü Randevular',
      'zh_Hans': '今天的约会',
    },
    'ryoxyyzt': {
      'en': 'View All',
      'ar': 'عرض الكل',
      'de': 'Alle ansehen',
      'es': 'Ver todo',
      'fr': 'Voir tout',
      'pt': 'Ver tudo',
      'ru': 'Посмотреть все',
      'tr': 'Hepsini gör',
      'zh_Hans': '查看全部',
    },
    'm929v9xi': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'tkru2ovh': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    'sro4bcxg': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    '00bqlnlz': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    'nr07wewc': {
      'en': 'Dashboard',
      'ar': 'لوحة القيادة',
      'de': 'Armaturenbrett',
      'es': 'Panel',
      'fr': 'Tableau de bord',
      'pt': 'Painel',
      'ru': 'Панель приборов',
      'tr': 'Gösterge Paneli',
      'zh_Hans': '仪表板',
    },
    'i1j111xk': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // vcard_screen
  {
    'xv0dqfc8': {
      'en': 'VCards',
      'ar': 'بطاقات فيديو',
      'de': 'VCards',
      'es': 'Tarjetas V',
      'fr': 'Cartes virtuelles',
      'pt': 'VCards',
      'ru': 'Видеокарты',
      'tr': 'VCard\'lar',
      'zh_Hans': '电子名片',
    },
    '0b5yuzlp': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // appointment_screen
  {
    'j1qb796r': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'j0a2339e': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    '7q1plnq9': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'xa87wpus': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    'gbdiajm8': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'wz8dh3hs': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    'uz663lz8': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    '6haxvic0': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    'gzd51k3u': {
      'en': 'Appointments',
      'ar': 'تعيينات',
      'de': 'Termine',
      'es': 'Equipo',
      'fr': 'Rendez-vous',
      'pt': 'Compromissos',
      'ru': 'Назначения',
      'tr': 'Randevular',
      'zh_Hans': '预约',
    },
    'giyqb9oq': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // enquiries_screen
  {
    'o0move6g': {
      'en': 'Enquiries',
      'ar': 'استفسارات',
      'de': 'Anfragen',
      'es': 'Consultas',
      'fr': 'Demandes de renseignements',
      'pt': 'Inquéritos',
      'ru': 'Запросы',
      'tr': 'Araştırma',
      'zh_Hans': '查询',
    },
    'hrx9hnj8': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'bhzpx70d': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    '7wpwdv2a': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'jnykkpdr': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'zb2cbx2s': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // setting_screen
  {
    'mg8rhguv': {
      'en': 'Edit Profile',
      'ar': 'تعديللف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'pt': 'Editar Perfil',
      'ru': 'Редактировать',
      'tr': 'Profili Düzenle',
      'zh_Hans': '编辑个人资料',
    },
    'y9n16027': {
      'en': 'Language',
      'ar': 'لغة',
      'de': 'Sprache',
      'es': 'Idioma',
      'fr': 'Langue',
      'pt': 'Linguagem',
      'ru': 'Язык',
      'tr': 'Dil',
      'zh_Hans': '语言',
    },
    'i7c0zshr': {
      'en': 'Change Password',
      'ar': 'تغيير كلمة المرور',
      'de': 'Kennwort ändern',
      'es': 'Cambiar la contraseña',
      'fr': 'Changer le mot de passe',
      'pt': 'Alterar a senha',
      'ru': 'Изменить пароль',
      'tr': 'Şifre değiştir',
      'zh_Hans': '更改密码',
    },
    'lgxuhg43': {
      'en': 'Enable Affiliation',
      'ar': 'تمكين الانتساب',
      'de': 'Zugehörigkeit aktivieren',
      'es': 'Habilitar afiliación',
      'fr': 'Activer l\'affiliation',
      'pt': 'Habilitar Afiliação',
      'ru': 'Включить принадлежность',
      'tr': 'İlişkilendirmeyi Etkinleştir',
      'zh_Hans': '启用隶属关系',
    },
    'xcggpv4p': {
      'en': 'Enable Add to contact',
      'ar': 'تمكين إضافة إلى جهة الاتصال',
      'de': 'Aktivieren Sie „Zum Kontakt hinzufügen“.',
      'es': 'Habilitar Agregar al contacto',
      'fr': 'Activer Ajouter au contact',
      'pt': 'Ativar Adicionar ao contato',
      'ru': 'Включить Добавить в контакт',
      'tr': 'Kişiye ekle\'yi etkinleştir',
      'zh_Hans': '启用添加到联系人',
    },
    'qbhjmxyf': {
      'en': 'Hide vCard Sticky Bar',
      'ar': 'إخفاء شريط لاصق vCard',
      'de': 'vCard Sticky Bar ausblenden',
      'es': 'Ocultar barra adhesiva de vCard',
      'fr': 'Masquer la barre collante vCard',
      'pt': 'Ocultar barra adesiva do vCard',
      'ru': 'Скрыть липкую панель vCard',
      'tr': 'vCard Yapışkan Çubuğunu Gizle',
      'zh_Hans': '隐藏 vCard 粘滞栏',
    },
    '0n5cykg2': {
      'en': 'WhatsApp Share',
      'ar': 'مشاركة واتساب',
      'de': 'WhatsApp-Freigabe',
      'es': 'Compartir WhatsApp',
      'fr': 'Partager WhatsApp',
      'pt': 'Compartilhar WhatsApp',
      'ru': 'WhatsApp Поделиться',
      'tr': 'WhatsApp Paylaş',
      'zh_Hans': 'WhatsApp 分享',
    },
    '2vqrk4yt': {
      'en': 'Settings',
      'ar': 'إعدادات',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'pt': 'Configurações',
      'ru': 'Настройки',
      'tr': 'Ayarlar',
      'zh_Hans': '设置',
    },
    'uzddh5zz': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // change_password_screen
  {
    'malgoxmk': {
      'en': 'Change Password',
      'ar': 'تغيير كلمة المرور',
      'de': 'Kennwort ändern',
      'es': 'Cambiar la contraseña',
      'fr': 'Changer le mot de passe',
      'pt': 'Alterar a senha',
      'ru': 'Изменить пароль',
      'tr': 'Şifre değiştir',
      'zh_Hans': '更改密码',
    },
    'xcayyr1i': {
      'en': 'Current Password:',
      'ar': 'كلمة السر الحالية:',
      'de': 'Aktuelles Passwort:',
      'es': 'Contraseña actual:',
      'fr': 'Mot de passe actuel:',
      'pt': 'Senha atual:',
      'ru': 'Текущий пароль:',
      'tr': 'Mevcut Şifre:',
      'zh_Hans': '当前密码：',
    },
    'gj7gq0fk': {
      'en': ' *',
      'ar': '*',
      'de': '*',
      'es': '*',
      'fr': '*',
      'pt': '*',
      'ru': '*',
      'tr': '*',
      'zh_Hans': '*',
    },
    'rm8akjbc': {
      'en': 'Current Password',
      'ar': 'كلمة السر الحالية',
      'de': 'Aktuelles Passwort',
      'es': 'Contraseña actual',
      'fr': 'Mot de passe actuel',
      'pt': 'Senha atual',
      'ru': 'Текущий пароль',
      'tr': 'Mevcut Şifre',
      'zh_Hans': '当前密码',
    },
    '3h03ny4j': {
      'en': 'New Password:',
      'ar': 'كلمة المرور الجديدة:',
      'de': 'Neues Kennwort:',
      'es': 'Nueva contraseña:',
      'fr': 'Nouveau mot de passe:',
      'pt': 'Nova Senha:',
      'ru': 'Новый пароль:',
      'tr': 'Yeni Şifre:',
      'zh_Hans': '新密码：',
    },
    'u6iv42vg': {
      'en': ' *',
      'ar': '*',
      'de': '*',
      'es': '*',
      'fr': '*',
      'pt': '*',
      'ru': '*',
      'tr': '*',
      'zh_Hans': '*',
    },
    '38oe3q7h': {
      'en': 'New Password',
      'ar': 'كلمة المرور الجديدة',
      'de': 'Neues Kennwort',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'pt': 'Nova Senha',
      'ru': 'Новый пароль',
      'tr': 'Yeni Şifre',
      'zh_Hans': '新密码',
    },
    '7aycies1': {
      'en': 'Confirm Password:',
      'ar': 'تأكيد كلمة المرور:',
      'de': 'Bestätige das Passwort:',
      'es': 'Confirmar Contraseña:',
      'fr': 'Confirmez le mot de passe:',
      'pt': 'Confirme sua senha:',
      'ru': 'Подтвердите пароль:',
      'tr': 'Şifreyi Onayla:',
      'zh_Hans': '确认密码：',
    },
    'c6hsm8d0': {
      'en': ' *',
      'ar': '*',
      'de': '*',
      'es': '*',
      'fr': '*',
      'pt': '*',
      'ru': '*',
      'tr': '*',
      'zh_Hans': '*',
    },
    'a73s21iu': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'pt': 'Confirme sua senha',
      'ru': 'Подтвердите пароль',
      'tr': 'Şifreyi Onayla',
      'zh_Hans': '确认密码',
    },
    '9jxexqm3': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'tr': 'Kaydetmek',
      'zh_Hans': '节省',
    },
    '6dvjt0n2': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
    '3x9wfr4k': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // edit_profile_screen
  {
    'xzao1gj9': {
      'en': 'Full Name:',
      'ar': 'الاسم الكامل:',
      'de': 'Vollständiger Name:',
      'es': 'Nombre completo:',
      'fr': 'Nom et prénom:',
      'pt': 'Nome completo:',
      'ru': 'Полное имя:',
      'tr': 'Ad Soyad:',
      'zh_Hans': '全名：',
    },
    'hiprfz0c': {
      'en': 'Enter First Name',
      'ar': 'أدخل الاسم الأول',
      'de': 'Bitte Vornamen eingeben',
      'es': 'Introduzca el nombre',
      'fr': 'Entrez votre prénom',
      'pt': 'Introduza o primeiro nome',
      'ru': 'Введите имя',
      'tr': 'Adını Girin',
      'zh_Hans': '输入名字',
    },
    'clqyndho': {
      'en': 'Enter Last Name',
      'ar': 'أدخل الاسم الأول',
      'de': 'Bitte Vornamen eingeben',
      'es': 'Introduzca el nombre',
      'fr': 'Entrez votre prénom',
      'pt': 'Introduza o primeiro nome',
      'ru': 'Введите имя',
      'tr': 'Adını Girin',
      'zh_Hans': '输入名字',
    },
    'dtstmqtx': {
      'en': 'Email:',
      'ar': 'بريد إلكتروني:',
      'de': 'Email:',
      'es': 'Correo electrónico:',
      'fr': 'E-mail:',
      'pt': 'E-mail:',
      'ru': 'Электронная почта:',
      'tr': 'E-posta:',
      'zh_Hans': '电子邮件：',
    },
    'hzqkgpzd': {
      'en': ' *',
      'ar': ' *',
      'de': ' *',
      'es': ' *',
      'fr': ' *',
      'pt': ' *',
      'ru': ' *',
      'tr': ' *',
      'zh_Hans': ' *',
    },
    'r7tg0ukf': {
      'en': 'Enter Email',
      'ar': 'أدخل البريد الإلكتروني',
      'de': 'Email eingeben',
      'es': 'Ingrese correo electrónico',
      'fr': 'Entrez l\'e-mail',
      'pt': 'Digite o e-mail',
      'ru': 'Введите адрес электронной почты',
      'tr': 'E-posta Girin',
      'zh_Hans': '输入电子邮件',
    },
    '1za1kahu': {
      'en': 'Contact Number:',
      'ar': 'رقم الاتصال:',
      'de': 'Kontakt Nummer:',
      'es': 'Número de contacto:',
      'fr': 'Numéro de contact:',
      'pt': 'Número de contato:',
      'ru': 'Контактный номер:',
      'tr': 'İletişim numarası:',
      'zh_Hans': '联系电话：',
    },
    '8eu3zng3': {
      'en': ' *',
      'ar': ' *',
      'de': ' *',
      'es': ' *',
      'fr': ' *',
      'pt': ' *',
      'ru': ' *',
      'tr': ' *',
      'zh_Hans': ' *',
    },
    'bi0q9hyu': {
      'en': 'Enter Contact number',
      'ar': 'أدخل رقم الاتصال',
      'de': 'Geben Sie die Kontaktnummer ein',
      'es': 'Ingrese el número de contacto',
      'fr': 'Entrez le numéro de contact',
      'pt': 'Digite o número de contato',
      'ru': 'Введите контактный номер',
      'tr': 'İletişim numarasını girin',
      'zh_Hans': '输入联系电话',
    },
    'gef46sip': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'tr': 'Kaydetmek',
      'zh_Hans': '节省',
    },
    'u8el6evt': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
    '2rucwo9a': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'pt': 'Editar Perfil',
      'ru': 'Редактировать профиль',
      'tr': 'Profili Düzenle',
      'zh_Hans': '编辑个人资料',
    },
    '9m5wjghs': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // business_card_screen
  {
    'w7cj5v2s': {
      'en': 'Business Cards',
      'ar': 'بطاقات العمل',
      'de': 'Visitenkarten',
      'es': 'Cartas de negocios',
      'fr': 'Cartes de visite',
      'pt': 'Cartões de negócios',
      'ru': 'Визитки',
      'tr': 'Kartvizitler',
      'zh_Hans': '商业名片',
    },
    'a19bsrp1': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'yiciai6r': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    '9iwqms5z': {
      'en': '   |   ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'l18wkyym': {
      'en': '  |  ',
      'ar': '  |  ',
      'de': '  |  ',
      'es': '  |  ',
      'fr': '  |  ',
      'pt': '  |  ',
      'ru': '  |  ',
      'tr': '  |  ',
      'zh_Hans': '  |  ',
    },
    'oxp3unm3': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // register_screen
  {
    'cgei5bnd': {
      'en': 'Register Account',
      'ar': 'تسجيل حساب',
      'de': 'Account registrieren',
      'es': 'Registrar Cuenta',
      'fr': 'Créer un compte',
      'pt': 'Registar Conta',
      'ru': 'Регистрация Аккаунта',
      'tr': 'Hesap Kaydı',
      'zh_Hans': '注册账户',
    },
    'yqqtpp25': {
      'en': 'Please enter your details',
      'ar': 'الرجاء إدخال التفاصيل الخاصة بك',
      'de': 'Bitte geben Sie Ihre Daten ein',
      'es': 'Por favor ingresa tus datos',
      'fr': 'Veuillez entrer vos coordonnées',
      'pt': 'Por favor insira seus dados',
      'ru': 'Пожалуйста, введите свои данные',
      'tr': 'Lütfen bilgilerinizi girin',
      'zh_Hans': '请输入您的详细信息',
    },
    '9ni1jqov': {
      'en': 'Enter Your First Name',
      'ar': 'أدخل اسمك الأول',
      'de': 'Geben Sie Ihren Vornamen ein',
      'es': 'Ponga su primer nombre',
      'fr': 'Entrez votre prénom',
      'pt': 'Digite seu primeiro nome',
      'ru': 'Введите свое имя',
      'tr': 'İlk adınızı girin',
      'zh_Hans': '输入您的名字',
    },
    'qf8w78qo': {
      'en': 'Enter Your Last Name',
      'ar': 'أدخل اسمك الأخير',
      'de': 'Geben Sie Ihren Nachnamen ein',
      'es': 'Ingrese su apellido',
      'fr': 'Entrez votre nom de famille',
      'pt': 'Digite seu sobrenome',
      'ru': 'Введите свою фамилию',
      'tr': 'Soyadınızı giriniz',
      'zh_Hans': '输入您的姓氏',
    },
    'esxemusr': {
      'en': 'Enter Your Email',
      'ar': 'أدخل بريدك الإلكتروني',
      'de': 'Geben sie ihre E-Mail Adresse ein',
      'es': 'Introduce tu correo electrónico',
      'fr': 'Entrer votre Email',
      'pt': 'Digite seu e-mail',
      'ru': 'Введите адрес электронной почты',
      'tr': 'E-postanızı giriniz',
      'zh_Hans': '输入你的电子邮箱',
    },
    'wgvyzwvt': {
      'en': 'Enter Your Password',
      'ar': 'ادخل رقمك السري',
      'de': 'Geben Sie Ihr Passwort ein',
      'es': 'Ingresa tu contraseña',
      'fr': 'Tapez votre mot de passe',
      'pt': 'Coloque sua senha',
      'ru': 'Введите ваш пароль',
      'tr': 'Şifrenizi girin',
      'zh_Hans': '输入您的密码',
    },
    'obbyo86y': {
      'en': 'Enter Your Confirm Password',
      'ar': 'تأكيد كلمة المرور الخاصة بك',
      'de': 'Ihr Bestätigungspasswort',
      'es': 'Su contraseña confirmada',
      'fr': 'Votre mot de passe de confirmation',
      'pt': 'Sua Confirmação de Senha',
      'ru': 'Ваш пароль для подтверждения',
      'tr': 'Onay Şifreniz',
      'zh_Hans': '您的确认密码',
    },
    '1cnl5cer': {
      'en': 'Register',
      'ar': 'يسجل',
      'de': 'Registrieren',
      'es': 'Registro',
      'fr': 'Registre',
      'pt': 'Registro',
      'ru': 'регистр',
      'tr': 'Kayıt olmak',
      'zh_Hans': '登记',
    },
    '0duuerwu': {
      'en': 'Already have an Account?',
      'ar': 'هل لديك حساب؟',
      'de': 'Sie haben bereits ein Konto?',
      'es': '¿Ya tienes una cuenta?',
      'fr': 'Vous avez déjà un compte?',
      'pt': 'Já tem uma conta?',
      'ru': 'У вас уже есть учетная запись?',
      'tr': 'Zaten hesabınız var mı?',
      'zh_Hans': '已经有帐户？',
    },
    'z8plp0bu': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'pt': 'Conecte-se',
      'ru': 'Авторизоваться',
      'tr': 'Giriş yapmak',
      'zh_Hans': '登录',
    },
    'mz8icuzj': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'pt': 'Lar',
      'ru': 'Дом',
      'tr': 'Ev',
      'zh_Hans': '家',
    },
  },
  // vcard_sheet
  {
    'czqtua31': {
      'en': 'QR Code',
      'ar': 'رمز الاستجابة السريعة',
      'de': 'QR-Code',
      'es': 'Código QR',
      'fr': 'QR Code',
      'pt': 'Código QR',
      'ru': 'QR код',
      'tr': 'QR kod',
      'zh_Hans': '二维码',
    },
    'pjqehk70': {
      'en': 'Appointment',
      'ar': 'ميعاد',
      'de': 'Termin',
      'es': 'Cita',
      'fr': 'Rendez-vous',
      'pt': 'Encontro',
      'ru': 'Встреча',
      'tr': 'Randevu',
      'zh_Hans': '预约',
    },
    'scgrnjh5': {
      'en': 'Enquiries',
      'ar': 'استفسارات',
      'de': 'Anfragen',
      'es': 'Consultas',
      'fr': 'Demandes de renseignements',
      'pt': 'Inquéritos',
      'ru': 'Запросы',
      'tr': 'Araştırma',
      'zh_Hans': '查询',
    },
    'nbadcbhy': {
      'en': 'Delete',
      'ar': 'يمسح',
      'de': 'Löschen',
      'es': 'Borrar',
      'fr': 'Supprimer',
      'pt': 'Excluir',
      'ru': 'Удалить',
      'tr': 'Silmek',
      'zh_Hans': '删除',
    },
    '8qp2hsel': {
      'en': 'Delete Vcard',
      'ar': 'حذف في كارد',
      'de': 'Vcard löschen',
      'es': 'Eliminar tarjeta V',
      'fr': 'Supprimer la carte virtuelle',
      'pt': 'Excluir Vcard',
      'ru': 'Удалить визитную карточку',
      'tr': 'Vcard\'ı sil',
      'zh_Hans': '删除电子名片',
    },
    'rjtl9wlc': {
      'en': 'Are you sure want to delete this VCard?',
      'ar': 'هل أنت متأكد أنك تريد حذف VCard هذه؟',
      'de': 'Möchten Sie diese VCard wirklich löschen?',
      'es': '¿Está seguro de que desea eliminar esta VCard?',
      'fr': 'Êtes-vous sûr de vouloir supprimer cette VCard ?',
      'pt': 'Tem certeza de que deseja excluir este VCard?',
      'ru': 'Вы уверены, что хотите удалить эту VCard?',
      'tr': 'Bu VCard\'ı silmek istediğinizden emin misiniz?',
      'zh_Hans': '您确定要删除此电子名片吗？',
    },
    '5837yt5h': {
      'en': 'QR Code',
      'ar': 'رمز الاستجابة السريعة',
      'de': 'QR-Code',
      'es': 'Código QR',
      'fr': 'QR Code',
      'pt': 'Código QR',
      'ru': 'QR код',
      'tr': 'QR kod',
      'zh_Hans': '二维码',
    },
    'om39cqak': {
      'en': 'Write NFC',
      'ar': 'اكتب نفك',
      'de': 'Schreiben Sie NFC',
      'es': 'Escribir NFC',
      'fr': 'Écrire NFC',
      'pt': 'Escreva NFC',
      'ru': 'Написать NFC',
      'tr': 'NFC yaz',
      'zh_Hans': '写入NFC',
    },
  },
  // drawer
  {
    'b3jasfwe': {
      'en': 'Dashboard',
      'ar': 'لوحة القيادة',
      'de': 'Armaturenbrett',
      'es': 'Panel',
      'fr': 'Tableau de bord',
      'pt': 'Painel',
      'ru': 'Панель приборов',
      'tr': 'Gösterge Paneli',
      'zh_Hans': '仪表板',
    },
    '5esgh4un': {
      'en': 'Scan Business Cards',
      'ar': 'مسح بطاقات العمل',
      'de': 'Visitenkarten scannen',
      'es': 'Escanear tarjetas de visita',
      'fr': 'Numériser des cartes de visite',
      'pt': 'Digitalize cartões de visita',
      'ru': 'Сканирование визитных карточек',
      'tr': 'Kartvizitleri Tara',
      'zh_Hans': '扫描名片',
    },
    '5pw0ml62': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
    'es398s13': {
      'en': 'VCards',
      'ar': 'بطاقات فيديو',
      'de': 'VCards',
      'es': 'Tarjetas V',
      'fr': 'Cartes virtuelles',
      'pt': 'VCards',
      'ru': 'Видеокарты',
      'tr': 'VCard\'lar',
      'zh_Hans': '电子名片',
    },
    'uvnyicos': {
      'en': 'Enquiries',
      'ar': 'استفسارات',
      'de': 'Anfragen',
      'es': 'Consultas',
      'fr': 'Demandes de renseignements',
      'pt': 'Inquéritos',
      'ru': 'Запросы',
      'tr': 'Araştırma',
      'zh_Hans': '查询',
    },
    'ujuhl9mw': {
      'en': 'Appointments',
      'ar': 'تعيينات',
      'de': 'Termine',
      'es': 'Equipo',
      'fr': 'Rendez-vous',
      'pt': 'Compromissos',
      'ru': 'Назначения',
      'tr': 'Randevular',
      'zh_Hans': '预约',
    },
    '7myfbppy': {
      'en': 'Business Cards',
      'ar': 'بطاقات العمل',
      'de': 'Visitenkarten',
      'es': 'Cartas de negocios',
      'fr': 'Cartes de visite',
      'pt': 'Cartões de negócios',
      'ru': 'Визитки',
      'tr': 'Kartvizitler',
      'zh_Hans': '商业名片',
    },
    'etqjz79k': {
      'en': 'Setting',
      'ar': 'جلسة',
      'de': 'Einstellung',
      'es': 'Configuración',
      'fr': 'Paramètre',
      'pt': 'Contexto',
      'ru': 'Параметр',
      'tr': 'Ayar',
      'zh_Hans': '环境',
    },
    'l0kd7rcm': {
      'en': 'Log out',
      'ar': 'تسجيل خروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'pt': 'Sair',
      'ru': 'Выйти',
      'tr': 'Çıkış Yap',
      'zh_Hans': '登出',
    },
  },
  // appointment_sheet
  {
    '466tlio2': {
      'en': '•',
      'ar': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'pt': '•',
      'ru': '•',
      'tr': '•',
      'zh_Hans': '•',
    },
    'xtmrhsl8': {
      'en': 'Mark as Completed',
      'ar': 'وضع علامة كمكتمل',
      'de': 'Als abgeschlossen markieren',
      'es': 'Marcar como completado',
      'fr': 'Marquer comme terminé',
      'pt': 'Marcar como concluído',
      'ru': 'Отметить как завершенное',
      'tr': 'Tamamlandı Olarak İşaretle',
      'zh_Hans': '标记为已完成',
    },
    'yjdr134k': {
      'en': 'Delete Appointment',
      'ar': 'حذف الموعد',
      'de': 'Termin löschen',
      'es': 'Eliminar cita',
      'fr': 'Supprimer le rendez-vous',
      'pt': 'Excluir compromisso',
      'ru': 'Удалить встречу',
      'tr': 'Randevuyu Sil',
      'zh_Hans': '删除预约',
    },
    'gddc3pb8': {
      'en': 'Delete Appointment',
      'ar': 'حذف الموعد',
      'de': 'Termin löschen',
      'es': 'Eliminar cita',
      'fr': 'Supprimer le rendez-vous',
      'pt': 'Excluir compromisso',
      'ru': 'Удалить встречу',
      'tr': 'Randevuyu Sil',
      'zh_Hans': '删除预约',
    },
    '8ozw55kd': {
      'en': 'Are you sure want to delete this appointment?',
      'ar': 'هل أنت متأكد أنك تريد حذف هذا الموعد؟',
      'de': 'Möchten Sie diesen Termin wirklich löschen?',
      'es': '¿Está seguro de que desea eliminar esta cita?',
      'fr': 'Êtes-vous sûr de vouloir supprimer ce rendez-vous ?',
      'pt': 'Tem certeza de que deseja excluir este compromisso?',
      'ru': 'Вы уверены, что хотите удалить эту встречу?',
      'tr': 'Bu randevuyu silmek istediğinizden emin misiniz?',
      'zh_Hans': '您确定要删除此约会吗？',
    },
  },
  // delete_dialog_box
  {
    'vs9ndxz8': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
    'l72rvcpp': {
      'en': 'Delete',
      'ar': 'يمسح',
      'de': 'Löschen',
      'es': 'Borrar',
      'fr': 'Supprimer',
      'pt': 'Excluir',
      'ru': 'Удалить',
      'tr': 'Silmek',
      'zh_Hans': '删除',
    },
  },
  // enquiry_sheet
  {
    '5wvlwvl0': {
      'en': 'Message:',
      'ar': 'رسالة:',
      'de': 'Nachricht:',
      'es': 'Mensaje:',
      'fr': 'Message:',
      'pt': 'Mensagem:',
      'ru': 'Сообщение:',
      'tr': 'İleti:',
      'zh_Hans': '信息：',
    },
    '9nxg8fm7': {
      'en': 'Delete Enquiries',
      'ar': 'حذف الاستفسارات',
      'de': 'Anfragen löschen',
      'es': 'Eliminar consultas',
      'fr': 'Supprimer les demandes',
      'pt': 'Excluir consultas',
      'ru': 'Удалить запросы',
      'tr': 'Soruları Sil',
      'zh_Hans': '删除查询',
    },
    'pddaljtn': {
      'en': 'Delete Enquiry',
      'ar': 'حذف الاستفسار',
      'de': 'Anfrage löschen',
      'es': 'Eliminar consulta',
      'fr': 'Supprimer la demande',
      'pt': 'Excluir consulta',
      'ru': 'Удалить запрос',
      'tr': 'Sorguyu Sil',
      'zh_Hans': '删除查询',
    },
    'cn8iygh6': {
      'en': 'Are you sure want to delete this enquiry?',
      'ar': 'هل أنت متأكد أنك تريد حذف هذا الاستفسار؟',
      'de': 'Möchten Sie diese Anfrage wirklich löschen?',
      'es': '¿Estás seguro de que deseas eliminar esta consulta?',
      'fr': 'Etes-vous sûr de vouloir supprimer cette demande ?',
      'pt': 'Tem certeza de que deseja excluir esta consulta?',
      'ru': 'Вы уверены, что хотите удалить этот запрос?',
      'tr': 'Bu sorguyu silmek istediğinizden emin misiniz?',
      'zh_Hans': '您确定要删除此查询吗？',
    },
  },
  // logout_dialog_box
  {
    'zhbckfxu': {
      'en': 'Logout',
      'ar': 'تسجيل خروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'pt': 'Sair',
      'ru': 'Выйти',
      'tr': 'Çıkış Yap',
      'zh_Hans': '登出',
    },
    'j446pvul': {
      'en': 'Are you sure want to Logout?',
      'ar': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'de': 'Möchten Sie sich wirklich abmelden?',
      'es': '¿Está seguro de que desea cerrar sesión?',
      'fr': 'Etes-vous sûr de vouloir vous déconnecter ?',
      'pt': 'Tem certeza de que deseja sair?',
      'ru': 'Вы уверены, что хотите выйти из системы?',
      'tr': 'Oturumu kapatmak istediğinizden emin misiniz?',
      'zh_Hans': '您确定要退出吗？',
    },
    '1w5hmry4': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
    '3jhq3lck': {
      'en': 'Logout',
      'ar': 'تسجيل خروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'pt': 'Sair',
      'ru': 'Выйти',
      'tr': 'Çıkış Yap',
      'zh_Hans': '登出',
    },
  },
  // select_group_dialog_box
  {
    'pav5knqn': {
      'en': 'Select Group',
      'ar': 'اختر مجموعة',
      'de': 'Wähle die Gruppe',
      'es': 'Selecciona grupo',
      'fr': 'Sélectionner un groupe',
      'pt': 'Selecione o grupo',
      'ru': 'Выберите группу',
      'tr': 'Grup Seç',
      'zh_Hans': '选择组',
    },
    'gwoconob': {
      'en': 'Remove',
      'ar': 'يزيل',
      'de': 'Entfernen',
      'es': 'Eliminar',
      'fr': 'Retirer',
      'pt': 'Remover',
      'ru': 'Удалять',
      'tr': 'Kaldırmak',
      'zh_Hans': '消除',
    },
    'jhx9r5x3': {
      'en': 'Add Group',
      'ar': 'أضف مجموعة',
      'de': 'Gruppe hinzufügen',
      'es': 'Añadir grupo',
      'fr': 'Ajouter un groupe',
      'pt': 'Adicionar grupo',
      'ru': 'Добавить группу',
      'tr': 'Grup ekle',
      'zh_Hans': '添加组',
    },
    '519lfi78': {
      'en': 'Add Group',
      'ar': 'أضف مجموعة',
      'de': 'Gruppe hinzufügen',
      'es': 'Añadir grupo',
      'fr': 'Ajouter un groupe',
      'pt': 'Adicionar grupo',
      'ru': 'Добавить группу',
      'tr': 'Grup ekle',
      'zh_Hans': '添加组',
    },
    'nl3mfnja': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'tr': 'Kaydetmek',
      'zh_Hans': '节省',
    },
  },
  // add_group_component
  {
    'avdfo1ha': {
      'en': 'Add Group',
      'ar': 'أضف مجموعة',
      'de': 'Gruppe hinzufügen',
      'es': 'Añadir grupo',
      'fr': 'Ajouter un groupe',
      'pt': 'Adicionar grupo',
      'ru': 'Добавить группу',
      'tr': 'Grup ekle',
      'zh_Hans': '添加组',
    },
    'qyw7qjzy': {
      'en': 'Group Name',
      'ar': 'أسم المجموعة',
      'de': 'Gruppenname',
      'es': 'Nombre del grupo',
      'fr': 'Nom de groupe',
      'pt': 'Nome do grupo',
      'ru': 'Имя группы',
      'tr': 'Grup ismi',
      'zh_Hans': '团队名字',
    },
    'xw06my7r': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
    'pdjihobs': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'tr': 'Kaydetmek',
      'zh_Hans': '节省',
    },
  },
  // nfc_write_sheet
  {
    'p8kqv4fo': {
      'en': 'Ready To Write',
      'ar': 'جاهز للكتابة',
      'de': 'Bereit zum Schreiben',
      'es': 'Listo para escribir',
      'fr': 'Prêt à écrire',
      'pt': 'Pronto para escrever',
      'ru': 'Готов написать',
      'tr': 'Yazmaya Hazır',
      'zh_Hans': '准备写作',
    },
    '94hehnjl': {
      'en': 'Move your phone closer to \nthe document.',
      'ar': 'قم بتقريب هاتفك من\nالمستند.',
      'de': 'Bewegen Sie Ihr Telefon näher an\ndas Dokument.',
      'es': 'Acerque su teléfono a\nel documento.',
      'fr': 'Rapprochez votre téléphone de\nle document.',
      'pt': 'Aproxime seu telefone de\no documento.',
      'ru': 'Поднесите телефон ближе к\nдокумент.',
      'tr': 'Telefonunuzu yakınlaştırın\ndöküman.',
      'zh_Hans': '将手机靠近\n该文件。',
    },
    'ozm3csxv': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
  },
  // scan_component
  {
    'g6ibpxlk': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'tr': 'İptal etmek',
      'zh_Hans': '取消',
    },
  },
  // empty_data_component
  {
    '94l07cwi': {
      'en': 'No Data Available!!',
      'ar': 'لا تتوافر بيانات!!',
      'de': 'Keine Daten verfügbar!!',
      'es': '¡¡Datos no disponibles!!',
      'fr': 'Pas de données disponibles!!',
      'pt': 'Nenhum dado disponível!!',
      'ru': 'Данные недоступны!!',
      'tr': 'Mevcut Veri Yok!!',
      'zh_Hans': '无可用数据！！',
    },
  },
  // delete_group_dialog_box
  {
    'ya1mvu3y': {
      'en': 'Remove Group',
      'ar': 'إزالة المجموعة',
      'de': 'Gruppe entfernen',
      'es': 'Quitar grupo',
      'fr': 'Supprimer le groupe',
      'pt': 'Remover grupo',
      'ru': 'Удалить группу',
      'tr': 'Grubu Kaldır',
      'zh_Hans': '删除组',
    },
    '6bpycp98': {
      'en': 'Remove Group',
      'ar': 'إزالة المجموعة',
      'de': 'Gruppe entfernen',
      'es': 'Quitar grupo',
      'fr': 'Supprimer le groupe',
      'pt': 'Remover grupo',
      'ru': 'Удалить группу',
      'tr': 'Grubu Kaldır',
      'zh_Hans': '删除组',
    },
  },
  // instruction_dialog
  {
    '3e7888cd': {
      'en': 'Steps to Open Reset Password Screen.',
      'ar': 'خطوات فتح شاشة إعادة تعيين كلمة المرور.',
      'de':
          'Schritte zum Öffnen des Bildschirms zum Zurücksetzen des Passworts.',
      'es': 'Pasos para abrir la pantalla Restablecer contraseña.',
      'fr': 'Étapes pour ouvrir l’écran de réinitialisation du mot de passe.',
      'pt': 'Etapas para abrir a tela de redefinição de senha.',
      'ru': 'Действия по открытию экрана сброса пароля.',
      'tr': 'Şifre Sıfırlama Ekranını Açma Adımları.',
      'zh_Hans': '打开重置密码屏幕的步骤。',
    },
    '4pub3o54': {
      'en': 'Go to settings and follow below steps.',
      'ar': 'انتقل إلى الإعدادات واتبع الخطوات أدناه.',
      'de':
          'Gehen Sie zu den Einstellungen und befolgen Sie die folgenden Schritte.',
      'es': 'Vaya a configuración y siga los pasos a continuación.',
      'fr': 'Accédez aux paramètres et suivez les étapes ci-dessous.',
      'pt': 'Vá para as configurações e siga as etapas abaixo.',
      'ru': 'Перейдите в настройки и выполните следующие действия.',
      'tr': 'Ayarlara gidin ve aşağıdaki adımları izleyin.',
      'zh_Hans': '转到设置并按照以下步骤操作。',
    },
    'srbg7bto': {
      'en': '1. Open app setting.',
      'ar': '1. افتح إعداد التطبيق.',
      'de': '1. App-Einstellung öffnen.',
      'es': '1. Abra la configuración de la aplicación.',
      'fr': '1. Ouvrez les paramètres de l\'application.',
      'pt': '1. Abra a configuração do aplicativo.',
      'ru': '1. Откройте настройки приложения.',
      'tr': '1. Uygulama ayarını açın.',
      'zh_Hans': '1. 打开应用程序设置。',
    },
    'mnx423h5': {
      'en': '2. Tap into “Open by default”.',
      'ar': '2. اضغط على \"فتح افتراضيًا\".',
      'de': '2. Tippen Sie auf „Standardmäßig öffnen“.',
      'es': '2. Toque \"Abrir por defecto\".',
      'fr': '2. Appuyez sur « Ouvrir par défaut ».',
      'pt': '2. Toque em “Abrir por padrão”.',
      'ru': '2. Нажмите «Открыть по умолчанию».',
      'tr': '2. \"Varsayılan olarak aç\" seçeneğine dokunun.',
      'zh_Hans': '2. 点击“默认打开”。',
    },
    'kbp5yjef': {
      'en': '3. Add link, and select available Link.',
      'ar': '3. أضف رابطًا، ثم حدد الرابط المتاح.',
      'de': '3. Link hinzufügen und verfügbaren Link auswählen.',
      'es': '3. Agregue el enlace y seleccione el enlace disponible.',
      'fr': '3. Ajoutez un lien et sélectionnez le lien disponible.',
      'pt': '3. Adicione o link e selecione o link disponível.',
      'ru': '3. Добавьте ссылку и выберите доступную ссылку.',
      'tr': '3. Bağlantı ekleyin ve mevcut Bağlantıyı seçin.',
      'zh_Hans': '3. 添加链接，然后选择可用的链接。',
    },
    'ppow7hza': {
      'en': '4. Now, open your reset password link in your mail box.',
      'ar':
          '4. الآن، افتح رابط إعادة تعيين كلمة المرور في صندوق البريد الخاص بك.',
      'de':
          '4. Öffnen Sie nun den Link zum Zurücksetzen Ihres Passworts in Ihrem Postfach.',
      'es':
          '4. Ahora, abra el enlace para restablecer la contraseña en su buzón de correo.',
      'fr':
          '4. Maintenant, ouvrez votre lien de réinitialisation de mot de passe dans votre boîte aux lettres.',
      'pt':
          '4. Agora, abra o link de redefinição de senha em sua caixa de correio.',
      'ru':
          '4. Теперь откройте ссылку для сброса пароля в своем почтовом ящике.',
      'tr': '4. Şimdi posta kutunuzdaki şifre sıfırlama bağlantısını açın.',
      'zh_Hans': '4. 现在，打开邮箱中的重置密码链接。',
    },
    '5n7l5g6u': {
      'en': 'Go to Setting',
      'ar': 'انتقل إلى الإعداد',
      'de': 'Gehen Sie zu Einstellung',
      'es': 'Ir a configuración',
      'fr': 'Allez dans Paramètres',
      'pt': 'Vá para configuração',
      'ru': 'Перейти к настройке',
      'tr': 'Ayara Git',
      'zh_Hans': '前往设置',
    },
  },
  // Miscellaneous
  {
    'emlaxqkx': {
      'en':
          'In order to scan for barcodes and QR codes, this app requires permission to access the camera.',
      'ar':
          'من أجل البحث عن الرموز الشريطية ورموز QR، يتطلب هذا التطبيق إذنًا للوصول إلى الكاميرا.',
      'de':
          'Um nach Barcodes und QR-Codes zu scannen, benötigt diese App die Erlaubnis, auf die Kamera zuzugreifen.',
      'es':
          'Para escanear códigos de barras y códigos QR, esta aplicación requiere permiso para acceder a la cámara.',
      'fr':
          'Afin de numériser des codes-barres et des codes QR, cette application nécessite une autorisation pour accéder à la caméra.',
      'pt':
          'Para digitalizar códigos de barras e códigos QR, este aplicativo requer permissão para acessar a câmera.',
      'ru':
          'Для сканирования штрих-кодов и QR-кодов этому приложению требуется разрешение на доступ к камере.',
      'tr':
          'Barkodları ve QR kodlarını taramak için bu uygulamanın kameraya erişim iznine ihtiyacı vardır.',
      'zh_Hans': '为了扫描条形码和二维码，此应用程序需要访问相机的权限。',
    },
    'kcglmo2n': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9jbvizuo': {
      'en':
          'In order to save contact, this app requires permission to access the contact',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kzgfqwxd': {
      'en': 'Allow NFC Permission for Read and Write NFC Cards.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'zd8zu4bj': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'c4dsezao': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'w9mq572h': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'dcgsvo5f': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'f55w16uu': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'v3xhl8u3': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'zflj63ri': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ny0cmlus': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'l71rqwjl': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'j9yhl7xn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jgriox45': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ym8h30k3': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2avu4iqx': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'r7znqgj4': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kyj0gr39': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6jxublw0': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '25ab0n8x': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ej3h14cd': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wu73s867': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'h4lb2x6z': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    's3dvl2h2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'lj4umspj': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'yvoo2o0c': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'qvftghvv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'x7y1wb4c': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
